### ISSUE TITLE
Optimize impacts of plugin, muc Caching of all experiment data

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_abconfig#13]
I'm seeing around 5-10 extra db calls per page load including some even if we don't even have any experiments setup. Ideally we should never hit the db on a page load.

The data in the experiments is fairly small and the whole thing, ie all active experiments should be in a single muc item in application scope.

Anytime you edit, disable, activate or change the condition sets on any experiment just re-save the entire muc item.

**Comment by Peterburnett** [comment]
MUC caching has been added in PR #14
