### ISSUE TITLE
The order of the condition sets in the edit form is not the same as shown in the experiments

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_abconfig#15]
I am guessing the edit form is natural db order (order inserted) vs the other page which is ordered by shortname?

**Comment by brendanheywood** [comment]
Ideally it would be good if here:

https://github.com/catalyst/moodle-tool_abconfig/blob/master/classes/form/edit_experiment.php#L104

did not touch the db at all and just called the experience_manager so all the db stuff is in one place

**Comment by Peterburnett** [comment]
Fixed
