### ISSUE TITLE
Avoid raw _GET access

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_abconfig#19]
https://github.com/catalyst/moodle-tool_abconfig/blob/master/lib.php#L35

https://github.com/catalyst/moodle-tool_abconfig/blob/master/lib.php#L44

**Comment by danmarsden** [comment]
@Peterburnett is the $_GET here really needed?
https://github.com/catalyst/moodle-tool_abconfig/blob/master/lib.php#L44
Can't you iterate over the list of $experiements to see if one exists?
especially as you check to see if the experiment exists in the array before you do anything with it here?
https://github.com/catalyst/moodle-tool_abconfig/blob/master/lib.php#L53
