### ISSUE TITLE
Add a condition so we can target specific user ids or usernames

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_abconfig#38]
* [x] each condition set should have another text area field which can accept a list of usernames or id numbers

**Comment by golenkovm** [comment]
This has been implemented

**Comment by brendanheywood** [comment]
I would have done this a little differently so it would be generic user attribute filters than just selecting specific users, made https://github.com/catalyst/moodle-tool_abconfig/issues/52
