### ISSUE TITLE
Full stack trace trace is not displayed when using the plugin 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_abconfig#58]
steps to replicate:

- hack into /calendar/view.php and add something like throw new dml_exception('dbdriverproblem', 1); to line 60 (after processing all variables).
- enabled debugging and displaying debug messages navigating to admin/settings.php?section=debugging 
- navigate to /calendar/view.php and confirm that you can see PHP  stack trace 
- disable debugging 
- create an experiment with for all users, including admins with following commands ["CFG,debug,32767","CFG,debugdisplay,1","js_header,console.log('Works');"]
- navigate to  /calendar/view.php and confirm that you don't see PHP stack trace, but you still can see 'Works' in js console

**Comment by dmitriim** [comment]
This happens because Moodle sets PHP errors earlier than calls "after_config"  hook. see https://github.com/moodle/moodle/blob/master/lib/setup.php#L702

**Comment by dmitriim** [comment]
Not sure about the best way to fix it. We can simply hardcode setting PHP debugging in the plugin the same way as it's in core. But not sure if this is the best solution.  @golenkovm @brendanheywood @Peterburnett @keevan  Any ideas?

**Comment by dmitriim** [comment]
I was able to get it working. The missing bit was forcing debugdeveloper to 1. So following config works as expected.

`["CFG,debug,32767","CFG,debugdisplay,1","CFG,debugdeveloper,1","js_header,console.log('Works');"]`

**Comment by brendanheywood** [comment]
I would reopen this and turn it into a documentation task.

**Comment by dmitriim** [comment]
@Peterburnett came up with an idea to have a specific experiment config for enabling debugging.E.g. `DEBUG,1`

**Comment by dmitriim** [comment]
I have created https://github.com/catalyst/moodle-tool_abconfig/issues/59
