### ISSUE TITLE
Testing for Moodle 4.1

### ISSUE THREAD

**Issue by sarahjcotton** [catalyst/moodle-tool_abconfig#60]
Validation on edit_conditions form can't run due to string/int operator issue.
Setting the value to 0 if an empty string is being evaluated fixes the problem.

**Comment by dmitriim** [comment]
@sarahjcotton should we close this one? I used this plugin in 4.1 and seems like it works ok.

**Comment by sarahjcotton** [comment]
@dmitriim Looks like it's been merged so please go ahead... thank you :)
