### ISSUE TITLE
Hooks implementation missing the during_initial_install handling

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-tool_abconfig#69]
The implementation in #66 results in the issue #68 because during_initial_install isn't handled

https://moodledev.io/docs/4.4/apis/core/hooks#example-of-hook-callback-registration

**Comment by leonstr** [comment]
Proposed fix in PR #70 .

**Comment by djarran** [comment]
This was implemented by @leonstr in pull request https://github.com/catalyst/moodle-tool_abconfig/pull/70 that is now merged. Closing as complete
