### ISSUE TITLE
For admins allow a specific optional url param override to force trigger an experiment conditions

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_abconfig#7]
ie with an experiment name of 'objectfs' (experimentshortname) and a condition set of 'tryfoo' then if you visit any page like

* [x] /course/view.php?id=1&objectfs=tryfoo

then it will force just this single page view into that experiment, for both request scope and session scope. You should be able to force multiple experiments at the same time.

In the experiment page construct a little helper which spits out these params so you can cut and paste it into any url, including an example link to dashboard which includes these params.

Also for this reason 'experimentshortname' needs to be a tighter just PARAM_ALPHANUM so it's a valid param

* [x] Also it would be also useful to simply let it work for admins, eg

/course/view.php?id=1&objectfs=auto

* [x] and finally, once you have tested it all, you probably just want an explicit option to allow it to run for admins, this would be a checkbox in the experiment table / ui

**Comment by Peterburnett** [comment]
Implemented in PR #11
